   
server:
  port: 8081
  
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/haha
      username: root
      password: 1234 
     
logging:
  level:
    com.yl.user.dao: DEBUG  